apiName: "Peters API"

assets:
  mappings:
    /assets: /
  overrides:
    /: ../IPSEN3-frontend/dist/

server:
  rootPath: /api/*
  adminContextPath: /admin
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081